<a href="https://colab.research.google.com/github/MarcusHu529/Fetal-State-Predictor/blob/main/AI_CLUB_PROJECT-3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import os

In [ ]:
path ="https://raw.githubusercontent.com/MSU-AI/Fetal-State-Predictor/main/AI_Club_2.csv"

In [ ]:
data = pd.read_csv(path,encoding='unicode_escape')

In [ ]:
data

FileName     Date      SegFile       b       e    LBE     LB   AC  \
0              NaN      NaN          NaN     NaN     NaN    NaN    NaN  NaN   
1     Variab10.txt  12/1/96  CTG0001.txt   240.0   357.0  120.0  120.0  0.0   
2       Fmcs_1.txt   5/3/96  CTG0002.txt     5.0   632.0  132.0  132.0  4.0   
3       Fmcs_1.txt   5/3/96  CTG0003.txt   177.0   779.0  133.0  133.0  2.0   
4       Fmcs_1.txt   5/3/96  CTG0004.txt   411.0  1192.0  134.0  134.0  2.0   
...            ...      ...          ...     ...     ...    ...    ...  ...   
2125  S8001045.dsp   6/6/98  CTG2127.txt  1576.0  3049.0  140.0  140.0  1.0   
2126  S8001045.dsp   6/6/98  CTG2128.txt  2796.0  3415.0  142.0  142.0  1.0   
2127           NaN      NaN          NaN     NaN     NaN    NaN    NaN  NaN   
2128           NaN      NaN          NaN     NaN     NaN    NaN    NaN  NaN   
2129           NaN      NaN          NaN     NaN     NaN    NaN    NaN  NaN   

         FM    UC  ...    C    D    E   AD   DE   LD   FS  SUSP  CLASS  NSP  
0       NaN   NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN    NaN  NaN  
1       0.0   0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  1.0   0.0    9.0  2.0  
2       0.0   4.0  ...  0.0  0.0  0.0  1.0  0.0  0.0  0.0   0.0    6.0  1.0  
3       0.0   5.0  ...  0.0  0.0  0.0  1.0  0.0  0.0  0.0   0.0    6.0  1.0  
4       0.0   6.0  ...  0.0  0.0  0.0  1.0  0.0  0.0  0.0   0.0    6.0  1.0  
...     ...   ...  ...  ...  ...  ...  ...  ...  ...  ...   ...    ...  ...  
2125    0.0   9.0  ...  0.0  0.0  1.0  0.0  0.0  0.0  0.0   0.0    5.0  2.0  
2126    1.0   5.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0    1.0  1.0  
2127    NaN   NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN    NaN  NaN  
2128    NaN   NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN    NaN  NaN  
2129  564.0  23.0  ...  NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN    NaN  NaN  

[2130 rows x 40 columns]

In [ ]:
data.isnull().sum()

FileName    4
Date        4
SegFile     4
b           4
e           4
LBE         4
LB          4
AC          4
FM          3
UC          3
ASTV        3
MSTV        3
ALTV        3
MLTV        3
DL          2
DS          2
DP          2
DR          2
Width       4
Min         4
Max         4
Nmax        4
Nzeros      4
Mode        4
Mean        4
Median      4
Variance    4
Tendency    4
A           4
B           4
C           4
D           4
E           4
AD          4
DE          4
LD          4
FS          4
SUSP        4
CLASS       4
NSP         4
dtype: int64

In [ ]:
miss_value=['N/a','na','NaN',np.nan]
data = pd.read_csv(path,na_values=miss_value)
data.isnull().sum()

FileName    4
Date        4
SegFile     4
b           4
e           4
LBE         4
LB          4
AC          4
FM          3
UC          3
ASTV        3
MSTV        3
ALTV        3
MLTV        3
DL          2
DS          2
DP          2
DR          2
Width       4
Min         4
Max         4
Nmax        4
Nzeros      4
Mode        4
Mean        4
Median      4
Variance    4
Tendency    4
A           4
B           4
C           4
D           4
E           4
AD          4
DE          4
LD          4
FS          4
SUSP        4
CLASS       4
NSP         4
dtype: int64

In [ ]:
data.isnull().any()

FileName    True
Date        True
SegFile     True
b           True
e           True
LBE         True
LB          True
AC          True
FM          True
UC          True
ASTV        True
MSTV        True
ALTV        True
MLTV        True
DL          True
DS          True
DP          True
DR          True
Width       True
Min         True
Max         True
Nmax        True
Nzeros      True
Mode        True
Mean        True
Median      True
Variance    True
Tendency    True
A           True
B           True
C           True
D           True
E           True
AD          True
DE          True
LD          True
FS          True
SUSP        True
CLASS       True
NSP         True
dtype: bool

In [ ]:
data=data.dropna()

In [ ]:
dummies=pd.get_dummies(data.NSP)
merged_data=pd.concat([data,dummies],axis='columns')
merged_data

FileName     Date      SegFile       b       e    LBE     LB   AC  \
1     Variab10.txt  12/1/96  CTG0001.txt   240.0   357.0  120.0  120.0  0.0   
2       Fmcs_1.txt   5/3/96  CTG0002.txt     5.0   632.0  132.0  132.0  4.0   
3       Fmcs_1.txt   5/3/96  CTG0003.txt   177.0   779.0  133.0  133.0  2.0   
4       Fmcs_1.txt   5/3/96  CTG0004.txt   411.0  1192.0  134.0  134.0  2.0   
5       Fmcs_1.txt   5/3/96  CTG0005.txt   533.0  1147.0  132.0  132.0  4.0   
...            ...      ...          ...     ...     ...    ...    ...  ...   
2122  S8001045.dsp   6/6/98  CTG2124.txt  2059.0  2867.0  140.0  140.0  0.0   
2123  S8001045.dsp   6/6/98  CTG2125.txt  1576.0  2867.0  140.0  140.0  1.0   
2124  S8001045.dsp   6/6/98  CTG2126.txt  1576.0  2596.0  140.0  140.0  1.0   
2125  S8001045.dsp   6/6/98  CTG2127.txt  1576.0  3049.0  140.0  140.0  1.0   
2126  S8001045.dsp   6/6/98  CTG2128.txt  2796.0  3415.0  142.0  142.0  1.0   

       FM   UC  ...   AD   DE   LD   FS  SUSP  CLASS  NSP  1.0  2.0  3.0  
1     0.0  0.0  ...  0.0  0.0  0.0  1.0   0.0    9.0  2.0    0    1    0  
2     0.0  4.0  ...  1.0  0.0  0.0  0.0   0.0    6.0  1.0    1    0    0  
3     0.0  5.0  ...  1.0  0.0  0.0  0.0   0.0    6.0  1.0    1    0    0  
4     0.0  6.0  ...  1.0  0.0  0.0  0.0   0.0    6.0  1.0    1    0    0  
5     0.0  5.0  ...  0.0  0.0  0.0  0.0   0.0    2.0  1.0    1    0    0  
...   ...  ...  ...  ...  ...  ...  ...   ...    ...  ...  ...  ...  ...  
2122  0.0  6.0  ...  0.0  0.0  0.0  0.0   0.0    5.0  2.0    0    1    0  
2123  0.0  9.0  ...  0.0  0.0  0.0  0.0   0.0    5.0  2.0    0    1    0  
2124  0.0  7.0  ...  0.0  0.0  0.0  0.0   0.0    5.0  2.0    0    1    0  
2125  0.0  9.0  ...  0.0  0.0  0.0  0.0   0.0    5.0  2.0    0    1    0  
2126  1.0  5.0  ...  0.0  0.0  0.0  0.0   0.0    1.0  1.0    1    0    0  

[2126 rows x 43 columns]

In [ ]:
merged_data = merged_data[['LB', 'FM', 'UC', 'ASTV','ALTV',1.0,2.0,3.0]]

In [ ]:
merged_data 

LB   FM   UC  ASTV  ALTV  1.0  2.0  3.0
1     120.0  0.0  0.0  73.0  43.0    0    1    0
2     132.0  0.0  4.0  17.0   0.0    1    0    0
3     133.0  0.0  5.0  16.0   0.0    1    0    0
4     134.0  0.0  6.0  16.0   0.0    1    0    0
5     132.0  0.0  5.0  16.0   0.0    1    0    0
...     ...  ...  ...   ...   ...  ...  ...  ...
2122  140.0  0.0  6.0  79.0  25.0    0    1    0
2123  140.0  0.0  9.0  78.0  22.0    0    1    0
2124  140.0  0.0  7.0  79.0  20.0    0    1    0
2125  140.0  0.0  9.0  78.0  27.0    0    1    0
2126  142.0  1.0  5.0  74.0  36.0    1    0    0

[2126 rows x 8 columns]

In [ ]:
x= merged_data.iloc[:, :5].values
y= merged_data.iloc[:, 5:].values

In [ ]:
x

array([[120.,   0.,   0.,  73.,  43.],
       [132.,   0.,   4.,  17.,   0.],
       [133.,   0.,   5.,  16.,   0.],
       ...,
       [140.,   0.,   7.,  79.,  20.],
       [140.,   0.,   9.,  78.,  27.],
       [142.,   1.,   5.,  74.,  36.]])

In [ ]:
y

array([[0, 1, 0],
       [1, 0, 0],
       [1, 0, 0],
       ...,
       [0, 1, 0],
       [0, 1, 0],
       [1, 0, 0]], dtype=uint8)

In [ ]:
x.shape

(2126, 5)

In [ ]:
y.shape

(2126, 3)

In [ ]:
!pip install keras-tuner --upgrade
!pip install tensorflow
!pip install keras-tuner -q

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 135 kB 5.4 MB/s 
     |████████████████████████████████| 1.6 MB 53.0 MB/s 
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import pandas as pd
from tensorflow import keras
from tensorflow.keras import layers
from keras_tuner.tuners import RandomSearch

In [ ]:
X=merged_data.iloc[:,0:5].values
Y=merged_data.iloc[:,5:].values

In [ ]:
X

array([[120.,   0.,   0.,  73.,  43.],
       [132.,   0.,   4.,  17.,   0.],
       [133.,   0.,   5.,  16.,   0.],
       ...,
       [140.,   0.,   7.,  79.,  20.],
       [140.,   0.,   9.,  78.,  27.],
       [142.,   1.,   5.,  74.,  36.]])

In [ ]:
Y

array([[0, 1, 0],
       [1, 0, 0],
       [1, 0, 0],
       ...,
       [0, 1, 0],
       [0, 1, 0],
       [1, 0, 0]], dtype=uint8)

In [ ]:
def build_model(hp):
  model=keras.Sequential()
  for i in range(hp.Int('num_layers',2,20)):
    model.add(layers.Dense(units=hp.Int('units_'+str(i),
                                        min_value=32,
                                        max_value=512,
                                        step=32),
                           activation='relu'))
    model.add(layers.Dense(3,activation='linear'))
    model.compile(optimizer=keras.optimizers.Adam(hp.Choice('learning_rate',[1e-2,1e-3,1e-4])),loss='categorical_crossentropy',metrics=['accuracy'])
    return model

In [ ]:
 tuner=RandomSearch(build_model,objective='val_accuracy',max_trials=5,executions_per_trial=3,directory='projectAI',project_name='Fetal_State_Predictor')

In [ ]:
tuner.search_space_summary()

Search space summary
Default search space size: 3
num_layers (Int)
{'default': None, 'conditions': [], 'min_value': 2, 'max_value': 20, 'step': 1, 'sampling': None}
units_0 (Int)
{'default': None, 'conditions': [], 'min_value': 32, 'max_value': 512, 'step': 32, 'sampling': None}
learning_rate (Choice)
{'default': 0.01, 'conditions': [], 'values': [0.01, 0.001, 0.0001], 'ordered': True}


In [ ]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)
train_test_split(x_train,y_train,train_size=0.8)